AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Processes charges for advertisers based on events put into queue 
Parameters:
  MongoUri:
    Type: AWS::SSM::Parameter::Value<String>
    Default: '/api/db/mongo_uri'
  StripeSecretKey:
    Type: AWS::SSM::Parameter::Value<String>
    Default: '/api/stripe/secret_key'
Resources:
  ProcessAdvertiserTransactionsDeadLetterQueue:
    Type: AWS::SQS::Queue
  ProcessAdvertiserTransactionsQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: process-advertiser-transactions-input
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt ProcessAdvertiserTransactionsDeadLetterQueue.Arn
        maxReceiveCount: 3
      VisibilityTimeout: 240
  ProcessAdvertiserTransactionsFunction:
    Type: AWS::Serverless::Function
    Properties:
      Timeout: 180
      Handler: index.handler
      Runtime: nodejs10.x
      CodeUri: ./
      Events:
        ProcessAdvertiserTransactionsEvent:
          Type: SQS
          Properties:
            Queue: !GetAtt ProcessAdvertiserTransactionsQueue.Arn
            BatchSize: 1
      Policies:
        - AmazonSQSFullAccess
        - AmazonDynamoDBFullAccess
        - Statement:
          - Effect: Allow
            Action:
              - 'kms:Decrypt'
              - 'kms:ListKeys'
            Resource: '*'
      Environment:
        Variables:
          MONGO_URI: !Ref MongoUri
          STRIPE_SECRET_KEY: !Ref StripeSecretKey
